---
title: "Reproducible Research Project 1"
author: "Van Wyk Burnett"
date: "27 March 2020"
output: html_document
---

## Activity Monitoring

This is the first project of the Reproducible Research model that analyse activity data.

```{r load data, echo=TRUE}
setwd("C:/Users/vwbur_000/Documents/R/csv files")
#Unzipfile
if(!file.exists("activity.csv")){
  unzip(filename)
}
#Read csv into R
activitydata <- read.csv("activity.csv")
library(ggplot2)
library(plyr)
library(lattice)
```

```{r }
#convert date to weekdays
activitydata$day <- weekdays(as.Date(activitydata$date))
activitydata$DateTime<- as.POSIXct(activitydata$date, format="%Y-%m-%d")
#remove missing values
cleaned <- activitydata[!is.na(activitydata$steps),]
#create a table with total steps per day
sumTable <- aggregate(activitydata$steps ~ activitydata$date, FUN=sum)
colnames(sumTable)<- c("Date", "Steps")
#histogram with total number of steps taken each day
hist(sumTable$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day")

#mean number of steps taken per day
as.integer(mean(sumTable$Steps))

## Median of Steps taken per day
as.integer(median(sumTable$Steps))
```

```{r average}
##create average number of steps per interval
intervalTable <- ddply(cleaned, .(interval), summarize, Avg = mean(steps))

##Create line plot of average number of steps per interval
p <- ggplot(intervalTable, aes(x=interval, y=Avg), xlab = "Interval", ylab="Average Number of Steps")
p + geom_line()+xlab("Interval")+ylab("Average Number of Steps")+ggtitle("Average Number of Steps per Interval")
```

```{r max}
##Maximum steps by interval
maxSteps <- max(intervalTable$Avg)
##Which interval contains the maximum average number of steps
intervalTable[intervalTable$Avg==maxSteps,1]
```

```{r missing values}
###Imputing missing data
## Create the average number of steps per weekday and interval
avgTable <- ddply(cleaned, .(interval, day), summarize, Avg = mean(steps))

## Create dataset with all NAs for substitution
nadata<- activitydata[is.na(activitydata$steps),]
## Merge NA data with average weekday interval for substitution
newdata<-merge(nadata, avgTable, by=c("interval", "day"))

## Reorder the new substituded data in the same format as clean data set
newdata2<- newdata[,c(6,4,1,2,5)]
colnames(newdata2)<- c("steps", "date", "interval", "day", "DateTime")

##Merge the NA averages and non NA data together
mergeData <- rbind(cleaned, newdata2)

```

```{r total steps per day}
#########################################################################
###Histogram of total number of steps taken each day, after missing values are imputed.
##Create sum of steps per date to compare with step 1
sumTable2 <- aggregate(mergeData$steps ~ mergeData$date, FUN=sum)
colnames(sumTable2)<- c("Date", "Steps")

## Mean of Steps with NA data taken care of
as.integer(mean(sumTable2$Steps))
## Median of Steps with NA data taken care of
as.integer(median(sumTable2$Steps))

## Creating the histogram of total steps per day, categorized by data set to show impact
hist(sumTable2$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day with NAs Imputed", col="Black")
hist(sumTable$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day with NAs Imputed", col="Grey", add=T)
legend("topright", c("Imputed Data", "Non-NA Data"), fill=c("black", "grey") )
```

```{r interval}
###Panel plot comparing tha ave number of steps taken per 5-min interval across weekdays and weekends.
## Create new category based on the days of the week
mergeData$DayCategory <- ifelse(mergeData$day %in% c("Saturday", "Sunday"), "Weekend", "Weekday")

## Summarize data by interval and type of day
intervalTable2 <- ddply(mergeData, .(interval, DayCategory), summarize, Avg = mean(steps))

##Plot data in a panel plot
xyplot(Avg~interval|DayCategory, data=intervalTable2, type="l",  layout = c(1,2),
       main="Average Steps per Interval Based on Type of Day", 
       ylab="Average Number of Steps", xlab="Interval")
```
